# Generated by Django 3.2 on 2023-05-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0004_auto_20230507_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stock_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('x_dividend_date', models.DateField(blank=True, null=True)),
                ('paid_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10, null=True)),
                ('upcoming_payout_date', models.DateField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
