# Generated by Django 4.2.3 on 2024-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='total_dividend_paied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
