# Generated by Django 4.2 on 2023-05-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_portfolioitem_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
