# Generated by Django 3.2 on 2023-05-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_portfolioitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfolioitem',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
