# Generated by Django 3.2 on 2023-05-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20230516_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('tax_free', 'Tax-Free'), ('non-registered', 'Non-Registered')], default=0, max_length=15),
            preserve_default=False,
        ),
    ]
