# Generated by Django 3.2 on 2023-05-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20230517_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
