# Generated by Django 3.2 on 2023-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_portfolioitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='distribution_per_share',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='paid_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='upcoming_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='x_dividend_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
