# Generated by Django 3.2 on 2023-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20230610_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='previous_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
