# Generated by Django 4.2.3 on 2023-10-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stock_previous_payout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='commission',
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BY', 'Market Buy'), ('SL', 'Market Sell'), ('DR', 'Dividend Reinvestment Buy')], max_length=2),
        ),
    ]
