# Generated by Django 4.2.3 on 2023-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_remove_transaction_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
