# Generated by Django 4.2.3 on 2023-10-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_transaction_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='account',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('tax_free', 'Tax-Free'), ('non-registered', 'Non-Registered'), ('FHSA', 'First Home Saving Account'), ('unknown', 'Unknown')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
