# Generated by Django 4.2.3 on 2023-11-06 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0016_portfolio_user_alter_portfolio_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('tax_free', 'Tax-Free'), ('non_registered', 'Non-Registered'), ('FHSA', 'First Home Saving Account'), ('unknown', 'Unknown')], max_length=15),
        ),
    ]
