# Generated by Django 4.2.3 on 2024-01-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_alter_stock_stock_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', max_length=5),
        ),
    ]
