# Generated by Django 4.2.3 on 2024-01-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_alert_portfolio'),
        ('stocks', '0021_stock_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
