# Generated by Django 4.2.3 on 2024-01-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_remove_portfolioitem_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='yahoo_ticker_symbol',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
