# Generated by Django 4.2.3 on 2024-01-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_stock_yahoo_ticker_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='yahoo_ticker_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
