# Generated by Django 4.2.3 on 2024-05-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_alter_stock_paid_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='x_dividend_date',
        ),
        migrations.CreateModel(
            name='Xdividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_dividend_date', models.DateField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
