# Generated by Django 4.2.3 on 2024-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_remove_stock_x_dividend_date_xdividend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='paid_period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=10),
        ),
    ]
